import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { Geist, Geist_Mono, Noto_Sans } from 'next/font/google';
import './globals.css';

const noto = Noto_Sans({
    variable: '--font-noto',
    subsets: ['latin'],
    weight: ['400', '700'],
});

const geistSans = Geist({
    variable: '--font-secondary',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

// Load custom font //
const font = localFont({
    variable: '--font-acma',
    src: [
        {
            path: '../../public/fonts/PPAcma-Semibold.otf',
        },
    ],
});

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body
                className={`${font.variable} ${geistSans.variable} ${noto.variable} ${geistMono.variable} antialiased max-w-[1800px] mx-auto relative w-full h-svh p-8 bg-primary text-secondary font-secondary font-light overflow-clip`}
            >
                {children}
            </body>
        </html>
    );
}
